### PR TITLE
added application/xhtml+xml support

### PR DESCRIPTION
**Pull request by mwette**
This is the pull request you asked for.  It only updated copy-mathml.js but worked in one case copying an equation into a popup copy/paste buffer in Firefox.

### CODE REVIEW

**Comment by mwette** [comment]
I think we may need to still add  `<html xmlns="http://www.w3.org/1999/xhtml>` and `</html>` around what currently exists.  See Sec 5 of [http://www.rfc-editor.org/rfc/rfc3236.txt](url).

**Comment by fred-wang** [comment]
Thanks for the pull request, can you please add the `<html>` wrapper around the copied `<math>`? I also I think XHTML must be well-formed and valid, so I guess doctype, `<head>`, `<body>` and other pieces are mandatory (and the `<math>` would be in the body). And the doctype should be XHTML+MathML+SVG I guess. https://www.w3.org/QA/2002/04/valid-dtd-list.html

**Comment by mwette** [comment]
Thanks.  I want to read-up and then will do that. — Matt

**Comment by mwette** [comment]
I have added the context including the DOCTYPE declaration, html, head, title and body.
However, I don't know how to quite test this right now.

**Comment by fred-wang** [comment]
Thanks @mwette! That seems to be what is needed. Regarding your comment, a well-formed document must have the XML definition and I believe what is done with the text to convert from javascript string to Unicode nsISupportsString is correct (at least that's similar to what I took from MDN). But I don't actually know the exact  rules to copy XML data to the clipboard nor am I aware of your use case. So I guess the best would be that you test it and see if that works as you want. For that purpose, you must install and use jpm. See details on MDN: https://developer.mozilla.org/en-US/Add-ons/SDK

**Comment by mwette** [comment]
I do have jpm and was able to run it in a “firefox sandbox” via “jpm run” and do a copy w/o errors.  

But I wanted to see a paste work.  The app I was using (pyqt) did not recognize the xhtml, though another app I was using at work (DOORS NG) was able to get the content correct.  I will look for something.

Thanks for the feedback.

Matt

**Comment by fred-wang** [comment]
Moved to https://github.com/fred-wang/webextension-mathml-view-source/issues/5

**Pull request closed without merging**
